package com.backend.servicerepo.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "user_management")
public class Student {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String schoolName;

    @DynamoDBAttribute
    private String address;

    @DynamoDBAttribute
    private CurriculumDetails curriculumDetails;
}
